version: '3'

services:
  mysql:
    image: "mysql:5.6"
    env_file:
      - ./config/mysql.env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always

  app:
    image: "romeoz/docker-nginx-php:5.6"
    env_file:
      - ./config/app.env
    volumes:
      - ./marmoles_travertino:/var/www/app/
    ports:
      - "8080:80"
    restart: always

  app_m:
    image: "romeoz/docker-nginx-php:5.6"
    env_file:
    - ./config/app_m.env
    volumes:
    - ./marmoles_travertino_m:/var/www/app/
    ports:
    - "8081:80"
    restart: always

  faraday_blink:
    image: "nginx:1.15.3"
    volumes:
      - ./faraday_blink/HTML:/usr/share/nginx/html:ro
    ports:
      - "8082:80"
    restart: always

  chain_reaction:
#    env_file:
#      - ./config/chain_reaction.env
    build:
      context: ./chain-reaction
#    volumes:
#    - ./chain-reaction:/app
    ports:
    - "8083:8080"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always