version: '3'

services:
  mysql:
    image: "mysql:5.6"
    env_file:
    - ./config/mysql.env
    volumes:
    - ./data:/var/lib/mysql
    ports:
    - 3306:3306
    restart: always

  app:
    image: "romeoz/docker-nginx-php:5.6"
    env_file:
      - ./config/app.env
    volumes:
      - ./marmol_travertino:/var/www/app/
    ports:
    - "8080:80"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    - 443:443
    restart: always