version: '3'
services:
  app:
    image: "romeoz/docker-nginx-php:5.6"
    volumes:
      - ./html:/var/www/app/
    ports:
    - "8080:80"
  mysql:
    image: "mysql:5.6"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "8081:3306"