version: '3'

services:
  app:
    image: "romeoz/docker-nginx-php:5.6"
    env_file:
      - ./config/app.env
    volumes:
      - ./html:/var/www/app/
    ports:
    - "8080:80"
    restart: always

  mysql:
    image: "mysql:5.6"
    env_file:
    - ./config/mysql.env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "8081:3306"
    restart: always
